### ISSUE TITLE
beefy fails on run

### ISSUE THREAD

**Issue by mattdesl** [stackgl/gl-compare#3]
I think switching to `budo` should fix.

```
> gl-compare@2.0.1 start /projects/oss/gl-compare
> cd example && beefy index.js:bundle.js --open

beefy (v2.1.5) is listening on http://127.0.0.1:9966
200    6ms       189B  / (generated)
buffer.js:219
    buf.copy(buffer, pos);
        ^

TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:219:9)
    at Stream.end (/projects/oss/gl-compare/node_modules/beefy/lib/accumulate-error.js:25:26)
    at _end (/projects/oss/gl-compare/node_modules/beefy/node_modules/through/index.js:61:9)
    at Stream.stream.end (/projects/oss/gl-compare/node_modules/beefy/node_modules/through/index.js:70:5)
    at Stream.onend (stream.js:59:10)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at drain (/projects/oss/gl-compare/node_modules/beefy/node_modules/through/index.js:33:23)
    at Stream.stream.queue.stream.push (/projects/oss/gl-compare/node_modules/beefy/node_modules/through/index.js:41:5)
    at Stream.end (/projects/oss/gl-compare/node_modules/beefy/node_modules/through/index.js:17:35)

npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/matt/.nvm/versions/node/v4.0.0/bin/node" "/Users/matt/.nvm/versions/node/v4.0.0/bin/npm" "run" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! gl-compare@2.0.1 start: `cd example && beefy index.js:bundle.js --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gl-compare@2.0.1 start script 'cd example && beefy index.js:bundle.js --open'.
npm ERR! This is most likely a problem with the gl-compare package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd example && beefy index.js:bundle.js --open
npm ERR! You can get their info via:
npm ERR!     npm owner ls gl-compare
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /projects/oss/gl-compare/npm-debug.log
```

**Comment by mattdesl** [comment]
Ok, this is fixed with #2. It looks like beefy is just providing misleading errors when a transform fails.
